#!/bin/sh
set -e
echo ">>> Writing config.js..."

cat > /usr/share/nginx/html/config.js << CONFIGEOF
// Runtime config - generated by docker entrypoint
// Everything proxied through nginx on port 3200 - no CORS issues
const API          = window.location.protocol + '//' + window.location.hostname + ':3200/api';
const CALDAV_URL   = window.location.protocol + '//' + window.location.hostname + ':3200/caldav/${CALDAV_USER}/calendar/';
const CALDAV_USER  = '${CALDAV_USER}';
const CALDAV_PASS  = '${CALDAV_PASS}';
const ADMIN_PIN_ENV = '${ADMIN_PIN}';
CONFIGEOF

echo ">>> config.js written:"
cat /usr/share/nginx/html/config.js
echo ">>> Starting nginx..."
exec nginx -g 'daemon off;'
